### ISSUE TITLE
Decoding problem in the keys

### ISSUE THREAD

**Issue by ghost** [kawww/Galaxy#1]
For example

http://galaxyos.io/stone.php?lang=&asset=NVdHCy89xRKXWUG9tXBFz9e5N4JjksACoA&showall=11&stone=1&group=no
![Screenshot from 2021-07-08 21-31-25](https://user-images.githubusercontent.com/76843085/124973324-0e6edd80-e034-11eb-9e3b-ee6b84a261be.png)

I have `RE:Q` key showed, when the kevacoin txid was provided originally in my wallet as the key for this data:
![Screenshot from 2021-07-08 21-31-07](https://user-images.githubusercontent.com/76843085/124973316-0b73ed00-e034-11eb-9370-1d349dcb4603.png)

_p.s. maybe this not related, but I have another issue for myself, just for note here:
https://github.com/kevacoin-project/kevacoin/issues/24_

**Comment by ghost** [comment]
Ok, saw the code - that is a string length cropping feature.

**Comment by kawww** [comment]
Yes, this is another method without ElectrumX.
